apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mmcharts-argo-ui
spec:
  selector:
    matchLabels:
      app: argo-ui
  template:
    metadata:
      labels:
        app: argo-ui
    spec:
      containers:
      - env:
        - name: ARGO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: IN_CLUSTER
          value: "true"
        - name: ENABLE_WEB_CONSOLE
          value: "{{ .Values.enable_web_console }}"
        - name: BASE_HREF
          value: {{ .Values.base_href }}
        #- name: FORCE_NAMESPACE_ISOLATION 
        #- value: "true"
        image: {{ .Values.images.argo_ui }}
        name: argo-ui
      serviceAccountName: argo-ui
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mmcharts-workflow-controller
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - argoproj/argoexec:v2.3.0
        #- argoproj/argoexec:v2.2.0
        command:
        - workflow-controller
        image: {{ .Values.images.controller }}
        name: workflow-controller
      serviceAccountName: argo
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

