# Default values for workflow-engine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


enable_web_console: true
base_href: /argo/

service:
  port: 80
  targetPort: 8001
  type: LoadBalancer

ingress:
  enabled: false
  hosts:
  - path: /argo

images:
  #argo_ui: argoproj/argoui:v2.2.1-37808b1
  argo_ui: argoproj/argoui:v2.3.0
  #controller: argoproj/workflow-controller:v2.2.0
  controller: argoproj/workflow-controller:v2.3.0

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector:
  role: default
