apiVersion: v1
appVersion: 1.13.1
description: Scales worker nodes within autoscaling groups.
engine: gotpl
home: https://github.com/kubernetes/autoscaler
icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
maintainers:
- email: mgoodness@gmail.com
  name: mgoodness
name: cluster-autoscaler
sources:
- https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
- https://github.com/spotinst/kubernetes-autoscaler/tree/master/cluster-autoscaler
version: 0.13.2
